name: graphs
base: core24
adopt-info: graphs
grade: stable 
confinement: strict
compression: lzo
license: GPL-3.0
architectures:
  - build-on: amd64
  - build-on: arm64


slots:
  graphs:
    interface: dbus
    bus: session
    name: se.sjoerd.Graphs

parts:
  numpy:
    source: https://github.com/numpy/numpy.git
    source-tag: 'v1.25.2'
    plugin: python
    build-environment:
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    python-packages:
      - scipy==1.11.2
      - python-dateutil==2.8.2
      - pyparsing==3.0.9
      - Pillow==10.0.0
      - packaging==23.1
      - contourpy==1.1.0
      - kiwisolver==1.4.5
      - fonttools==4.41.1
      - cycler==0.11.0
      - matplotlib==3.8.0
      - numexpr==2.8.6
      - mpmath==1.3.0
      - sympy==1.12
    prime:
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -pyvenv.cfg
      - -share
      - -include
      - -lib
      - -lib64
      - -usr/lib/python3/dist-packages/pip*
      - -usr/lib/python3/dist-packages/setuptools*
      - -usr/lib/python3/dist-packages/pkg_resources*
    organize: 
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages
      
  graphs:
    after: [ numpy ]
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/snap/graphs/current/usr
      - --buildtype=release
    build-snaps:
      - blueprint-compiler/latest/stable
      - gnome-46-2404-sdk/latest/edge
      - gnome-46-2404/latest/edge      
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH
      - GI_TYPELIB_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-46-2404-sdk/current/usr/lib/girepository-1.0
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/graphs/current/usr/bin/graphs
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/graphs/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    organize:
      snap/graphs/current/usr: usr
    parse-info: [usr/share/appdata/se.sjoerd.Graphs.appdata.xml]
    
    
apps:
  graphs:
    command: usr/bin/graphs
    desktop: usr/share/applications/se.sjoerd.Graphs.desktop
    common-id: se.sjoerd.Graphs
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$GI_TYPELIB_PATH